version: "2"
services:
    app:
        container_name: "react-cli-container"
        image: react-cli-image
        build: .
        command: ["yarn", "start"]
        ports:
            - 8080:3000
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
